# **Linear Regression on Artificially Generated Data**

## Importing Libraries

In [46]:
import pandas as pd
import numpy as np
import plotly as plt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

## Generating Dataset

In [3]:
from sklearn.datasets import make_regression

In [4]:
# without coeficient of underline model
X, y = make_regression( n_samples=500, n_features=5, coef=False, bias=12, noise = 10, random_state=2529)

In [5]:
# with coeficient of underline model 
X, y, w = make_regression( n_samples=500, n_features=5, coef=True, bias=12, noise = 10, random_state=2529)

In [6]:
# coefficients of X
w

array([29.45661718, 60.14529878, 61.7409438 , 13.32437893, 99.08122896])

In [7]:
X.shape, y.shape

((500, 5), (500,))

## Getting first  five rows of Target variable (y) and Features (X)

In [8]:
X[0:5]

array([[ 0.77913208, -1.09701784, -0.14239962,  1.02427891, -1.0708024 ],
       [-0.6925009 ,  0.45535977,  0.34707569, -0.32456746,  0.21970203],
       [-0.03901601, -0.3265115 ,  0.59793721,  0.61686653, -0.6237489 ],
       [-0.61566117, -0.11782129, -0.98234619, -0.78292727,  0.42713048],
       [ 1.30822207, -0.72541559,  0.60187975,  0.33285998,  1.48506184]])

In [9]:
y[0:5]

array([-136.21858395,   49.83118244,  -29.81097858,  -31.74001475,
        193.0687778 ])

## Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, train_size = 0.8, random_state = 2529)

In [13]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((400, 5), (400,), (100, 5), (100,))

## Model Fitting

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
lr = LinearRegression()

In [16]:
lr.fit(X_train, y_train)

LinearRegression()

## Model Testing

In [17]:
y_pred = lr.predict(X_test)

In [19]:
# Coefficients of Regression
lr.coef_

array([30.10559935, 59.93620908, 61.07702451, 13.57262251, 98.74992116])

In [25]:
lr.intercept_

12.665404661160121

In [18]:
from sklearn.metrics import r2_score, mean_squared_error

In [20]:
mean_squared_error(y_test, y_pred)

91.3123031096057

In [21]:
r2_score(y_test, y_pred) # 99.41%

0.9941054475789216